Question 1 (NumPy) – Titanic Dataset Survival Analysis 
1. Load the Titanic dataset using Pandas and convert the following numeric columns into a 
NumPy array: 
o age, fare, and survived. 
2. Using NumPy (not Pandas), perform the following: 
o a) Remove rows with missing values in any of the selected columns. 
o b) Normalize age and fare columns using Z-score normalization. 
o c) Compute the mean age and mean fare for: 
▪ passengers who survived 
▪ passengers who did not survive 
o d) Use np.where() to classify fare as: 
▪ "Low" if fare < mean, 
▪ "High" otherwise. 

In [1]:
import pandas as pd
import numpy as np

In [2]:
titanic_df = pd.read_csv('Titanic-Dataset.csv')

converting age, fare, and survived into numpy arrays

In [7]:
selected_columns = titanic_df[['Age', 'Fare', 'Survived']].to_numpy()

In [27]:
selected_columns

array([[22.    ,  7.25  ,  0.    ],
       [38.    , 71.2833,  1.    ],
       [26.    ,  7.925 ,  1.    ],
       ...,
       [    nan, 23.45  ,  0.    ],
       [26.    , 30.    ,  1.    ],
       [32.    ,  7.75  ,  0.    ]], shape=(891, 3))

removing nan values

In [8]:
cleaned_array = selected_columns[~np.isnan(selected_columns).any(axis=1)]

In [28]:
cleaned_array

array([[22.    ,  7.25  ,  0.    ],
       [38.    , 71.2833,  1.    ],
       [26.    ,  7.925 ,  1.    ],
       ...,
       [19.    , 30.    ,  1.    ],
       [26.    , 30.    ,  1.    ],
       [32.    ,  7.75  ,  0.    ]], shape=(714, 3))

accessing each terms in a matrix formate to columns

In [9]:
ages = cleaned_array[:, 0]
fares = cleaned_array[:, 1]
survived = cleaned_array[:, 2]

In [30]:
ages

array([22.  , 38.  , 26.  , 35.  , 35.  , 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 14.  , 55.  ,  2.  , 31.  , 35.  ,
       34.  , 15.  , 28.  ,  8.  , 38.  , 19.  , 40.  , 66.  , 28.  ,
       42.  , 21.  , 18.  , 14.  , 40.  , 27.  ,  3.  , 19.  , 18.  ,
        7.  , 21.  , 49.  , 29.  , 65.  , 21.  , 28.5 ,  5.  , 11.  ,
       22.  , 38.  , 45.  ,  4.  , 29.  , 19.  , 17.  , 26.  , 32.  ,
       16.  , 21.  , 26.  , 32.  , 25.  ,  0.83, 30.  , 22.  , 29.  ,
       28.  , 17.  , 33.  , 16.  , 23.  , 24.  , 29.  , 20.  , 46.  ,
       26.  , 59.  , 71.  , 23.  , 34.  , 34.  , 28.  , 21.  , 33.  ,
       37.  , 28.  , 21.  , 38.  , 47.  , 14.5 , 22.  , 20.  , 17.  ,
       21.  , 70.5 , 29.  , 24.  ,  2.  , 21.  , 32.5 , 32.5 , 54.  ,
       12.  , 24.  , 45.  , 33.  , 20.  , 47.  , 29.  , 25.  , 23.  ,
       19.  , 37.  , 16.  , 24.  , 22.  , 24.  , 19.  , 18.  , 19.  ,
       27.  ,  9.  , 36.5 , 42.  , 51.  , 22.  , 55.5 , 40.5 , 51.  ,
       16.  , 30.  ,

In [31]:
survived

array([0., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 1., 0., 0.,
       0., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1.,
       1., 0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0.,
       1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0.,
       0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0.,
       0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 0.,
       1., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 1., 0., 1.,
       0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0.,
       0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
       0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0.,
       1., 0., 0., 1., 0.

In [32]:
fares

array([  7.25  ,  71.2833,   7.925 ,  53.1   ,   8.05  ,  51.8625,
        21.075 ,  11.1333,  30.0708,  16.7   ,  26.55  ,   8.05  ,
        31.275 ,   7.8542,  16.    ,  29.125 ,  18.    ,  26.    ,
        13.    ,   8.0292,  35.5   ,  21.075 ,  31.3875, 263.    ,
        27.7208,  10.5   ,  82.1708,  52.    ,   8.05  ,  18.    ,
        11.2417,   9.475 ,  21.    ,  41.5792,   7.8792,  17.8   ,
        39.6875,   7.8   ,  76.7292,  26.    ,  61.9792,  10.5   ,
         7.2292,  27.75  ,  46.9   ,   7.2292,  80.    ,  83.475 ,
        27.9   ,  10.5   ,   8.1583,   7.925 ,   8.6625,  10.5   ,
        46.9   ,  73.5   ,  14.4542,  56.4958,   7.65  ,  29.    ,
        12.475 ,   9.    ,   9.5   ,  47.1   ,  10.5   ,  15.85  ,
        34.375 , 263.    ,   8.05  ,   8.05  ,   7.8542,  61.175 ,
        20.575 ,   7.25  ,  34.6542,  63.3583,  23.    ,  26.    ,
         7.8958,  77.2875,   8.6542,   7.925 ,   7.8958,   7.65  ,
         7.8958,  52.    ,  14.4542,   8.05  ,   9.825 ,  14.4

Normalize age and fare columns using Z-score normalization.

In [10]:
ages_z = (ages - np.mean(ages)) / np.std(ages)
fares_z = (fares - np.mean(fares)) / np.std(fares)

In [18]:
ages_z

array([-0.53037664,  0.57183099, -0.25482473,  0.36516706,  0.36516706,
        1.67403863, -1.90813618, -0.18593675, -1.08148046, -1.77036023,
        1.94959054, -0.6681526 ,  0.64071897, -1.08148046,  1.74292661,
       -1.90813618,  0.08961515,  0.36516706,  0.29627909, -1.01259248,
       -0.11704878, -1.49480832,  0.57183099, -0.73704057,  0.70960695,
        2.50069435, -0.11704878,  0.8473829 , -0.59926462, -0.80592855,
       -1.08148046,  0.70960695, -0.18593675, -1.83924821, -0.73704057,
       -0.80592855, -1.5636963 , -0.59926462,  1.32959874, -0.0481608 ,
        2.43180638, -0.59926462, -0.08260479, -1.70147225, -1.28814439,
       -0.53037664,  0.57183099,  1.05404683, -1.77036023, -0.0481608 ,
       -0.73704057, -0.87481653, -0.25482473,  0.15850313, -0.9437045 ,
       -0.59926462, -0.25482473,  0.15850313, -0.32371271, -1.98873512,
        0.02072718, -0.53037664, -0.0481608 , -0.11704878, -0.87481653,
        0.22739111, -0.9437045 , -0.46148866, -0.39260069, -0.04

In [19]:
fares_z

array([-5.18977865e-01,  6.91896750e-01, -5.06213563e-01,  3.48049152e-01,
       -5.03849804e-01,  3.24647932e-01, -2.57546055e-01, -4.45544364e-01,
       -8.74347866e-02, -3.40277640e-01, -1.54013385e-01, -5.03849804e-01,
       -6.46632722e-02, -5.07552397e-01, -3.53514694e-01, -1.05319937e-01,
       -3.15694541e-01, -1.64413927e-01, -4.10244924e-01, -5.04243133e-01,
        1.52318019e-02, -2.57546055e-01, -6.25358885e-02,  4.31727425e+00,
       -1.31873467e-01, -4.57520116e-01,  8.97780210e-01,  3.27248068e-01,
       -5.03849804e-01, -3.15694541e-01, -4.43494512e-01, -4.76902945e-01,
       -2.58964310e-01,  1.30189940e-01, -5.07079645e-01, -3.19476556e-01,
        9.44177482e-02, -5.08577323e-01,  7.94879137e-01, -1.64413927e-01,
        5.15955505e-01, -4.57520116e-01, -5.19371195e-01, -1.31321293e-01,
        2.30806676e-01, -5.19371195e-01,  8.56730216e-01,  9.22442732e-01,
       -1.28484781e-01, -4.57520116e-01, -5.01801843e-01, -5.06213563e-01,
       -4.92267382e-01, -

Compute the mean age and mean fare

In [11]:
mean_age_survived = np.mean(ages[survived == 1])
mean_fare_survived = np.mean(fares[survived == 1])
mean_age_not_survived = np.mean(ages[survived == 0])
mean_fare_not_survived = np.mean(fares[survived == 0])

In [ ]:
mean_age_survived


np.float64(22.96545636792453)

In [15]:
mean_fare_survived

np.float64(51.843205172413796)

In [16]:
mean_age_not_survived

np.float64(30.62617924528302)

In [17]:
mean_fare_not_survived

np.float64(22.96545636792453)

Use np.where() to classify fare

In [12]:
fare_mean = np.mean(fares)
fare_class = np.where(fares < fare_mean, "Low", "High")

In [14]:
fare_class[:10] 

array(['Low', 'High', 'Low', 'High', 'Low', 'High', 'Low', 'Low', 'Low',
       'Low'], dtype='<U4')

Question 2 (Pandas) – Iris Dataset Summary Report 
1. Load the Iris dataset using Pandas. 
2. Create a new column called petal_ratio = petal_length / petal_width. 
3. Answer the following: 
o a) What is the average petal_ratio per species? 
o b) Which species has the highest standard deviation in sepal_length? 
o c) Filter the dataset to only include rows where sepal_width is above the overall 
mean. 
o d) Split the DataFrame into two subsets: 
▪ One with petal_ratio < 2 
▪ One with petal_ratio ≥ 2 
▪ Then stack them vertically using pd.concat. 

Load the Iris dataset using Pandas.

In [54]:
iris_df = pd.read_excel("iris.xlsx")
iris_df.head()


sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

Create a new column called petal_ratio = petal_length / petal_width.

In [41]:
iris_df["petal_ratio"] = iris_df["petal.length"] / iris_df["petal.width"]

In [42]:
iris_df["petal_ratio"] 

0      7.000000
1      7.000000
2      6.500000
3      7.500000
4      7.000000
         ...   
145    2.260870
146    2.631579
147    2.600000
148    2.347826
149    2.833333
Name: petal_ratio, Length: 150, dtype: float64

What is the average petal_ratio per species? 

In [43]:
avg_petal_ratio = iris_df.groupby("variety")["petal_ratio"].mean()

In [44]:
avg_petal_ratio

variety
Setosa        6.908000
Versicolor    3.242837
Virginica     2.780662
Name: petal_ratio, dtype: float64

Which species has the highest standard deviation in sepal_length? 

In [45]:
std_sepal_length = iris_df.groupby("variety")["sepal.length"].std()
species_highest_std = std_sepal_length.idxmax()

In [46]:
std_sepal_length

variety
Setosa        0.352490
Versicolor    0.516171
Virginica     0.635880
Name: sepal.length, dtype: float64

In [47]:
species_highest_std

'Virginica'

Split the DataFrame into two subsets:

Filter the dataset to only include rows where sepal_width is above the overall 
mean.

In [48]:
mean_sepal_width = iris_df["sepal.width"].mean()
filtered_df = iris_df[iris_df["sepal.width"] > mean_sepal_width]

In [49]:
mean_sepal_width

np.float64(3.0573333333333337)

In [50]:
filtered_df

sepal.length  sepal.width  petal.length  petal.width    variety  \
0             5.1          3.5           1.4          0.2     Setosa   
2             4.7          3.2           1.3          0.2     Setosa   
3             4.6          3.1           1.5          0.2     Setosa   
4             5.0          3.6           1.4          0.2     Setosa   
5             5.4          3.9           1.7          0.4     Setosa   
..            ...          ...           ...          ...        ...   
140           6.7          3.1           5.6          2.4  Virginica   
141           6.9          3.1           5.1          2.3  Virginica   
143           6.8          3.2           5.9          2.3  Virginica   
144           6.7          3.3           5.7          2.5  Virginica   
148           6.2          3.4           5.4          2.3  Virginica   

     petal_ratio  
0       7.000000  
2       6.500000  
3       7.500000  
4       7.000000  
5       4.250000  
..           ...  
140     2.333333  
141     2.217391  
143     2.565217  
144     2.280000  
148     2.347826  

[67 rows x 6 columns]

stack them vertically using pd.concat. 

In [51]:
subset_lt_2 = iris_df[iris_df["petal_ratio"] < 2]
subset_ge_2 = iris_df[iris_df["petal_ratio"] >= 2]
combined_df = pd.concat([subset_lt_2, subset_ge_2], ignore_index=True)

In [52]:
combined_df.shape

(150, 6)

In [53]:
combined_df

sepal.length  sepal.width  petal.length  petal.width    variety  \
0             5.1          3.5           1.4          0.2     Setosa   
1             4.9          3.0           1.4          0.2     Setosa   
2             4.7          3.2           1.3          0.2     Setosa   
3             4.6          3.1           1.5          0.2     Setosa   
4             5.0          3.6           1.4          0.2     Setosa   
..            ...          ...           ...          ...        ...   
145           6.7          3.0           5.2          2.3  Virginica   
146           6.3          2.5           5.0          1.9  Virginica   
147           6.5          3.0           5.2          2.0  Virginica   
148           6.2          3.4           5.4          2.3  Virginica   
149           5.9          3.0           5.1          1.8  Virginica   

     petal_ratio  
0       7.000000  
1       7.000000  
2       6.500000  
3       7.500000  
4       7.000000  
..           ...  
145     2.260870  
146     2.631579  
147     2.600000  
148     2.347826  
149     2.833333  

[150 rows x 6 columns]